import { useState } from "react";
import { GoDotFill } from "react-icons/go";
import { AiOutlineDownload } from "react-icons/ai";

const ReportsTable = () => {
  const allReports = [
    {
      name: "FE cohort 3 report.pdf",
      user: "Sarah Jenkins",
      department: "Engineering",
      date: "April 12, 2026",
      status: "Ready",
    },
    {
      name: "Q1 Learning_Audit_pdf",
      user: "Marcus Thorne",
      department: "Human Resources",
      date: "Oct 08, 2026",
      status: "Processing",
    },
    {
      name: "Team allocation summary.xlsx",
      user: "Sarah Jenkins",
      department: "Engineering",
      date: "Oct 05, 2026",
      status: "Ready",
    },
    {
      name: "Q3 Engagement Metrics.pdf",
      user: "Emily Davis",
      department: "Sales",
      date: "Sept 20, 2026",
      status: "Ready",
    },
    {
      name: "2026 Training Feedback.xlsx",
      user: "Michael Lee",
      department: "Customer Support",
      date: "Sept 15, 2026",
      status: "Processing",
    },
    {
      name: "Leadership Development Report.pdf",
      user: "Jessica Brown",
      department: "Management",
      date: "Sept 10, 2026",
      status: "Ready",
    },
    {
      name: "Q2 Course Completion Rates.pdf",
      user: "David Wilson",
      department: "Engineering",
      date: "Aug 30, 2026",
      status: "Ready",
    },
    {
      name: "Employee Satisfaction Survey.xlsx",
      user: "Emily Davis",
      department: "Sales",
      date: "Aug 25, 2026",
      status: "Processing",
    },
    {
      name: "2026 Learning Trends.pdf",
      user: "Michael Lee",
      department: "Customer Support",
      date: "Aug 20, 2026",
      status: "Ready",
    },
    {
      name: "2026 Learning Trends.pdf",
      user: "Michael Lee",
      department: "Customer Support",
      date: "Aug 20, 2026",
      status: "Ready",
    },
  ];

  const [search, setSearch] = useState("");
  const [currentPage, setCurrentPage] = useState(1);

  const itemsPerPage = 3;

  //FILTER function
  const filtered = allReports.filter((report) =>
    report.name.toLowerCase().includes(search.toLowerCase()),
  );

  // Pagination
  const totalPages = Math.ceil(filtered.length / itemsPerPage);

  const currentData = filtered.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage,
  );

  return (
    <div className="bg-[#FFFFFF] rounded-lg h-130 shadow-sm mt-6">
      {/* HEADER */}
      <div className="flex justify-between items-center p-6 border-b border-[#E5E7EB]">
        <h2 className="font-extrabold text-[20px] text-[#001C3B]">
          Recent Generated Reports
        </h2>

        <input
          type="text"
          placeholder="Search reports..."
          className="w-[256px] h-10  rounded-lg outline-none bg-[#0029F50D] px-10 font-semibold text-[14px] placeholder:text-[#6B7280]"
          value={search}
          onChange={(e) => {
            setSearch(e.target.value);
            setCurrentPage(1);
          }}
        />
      </div>

      {/* TABLE */}
      <table className="w-full text-sm mt-3">
        <thead className="text-gray-500 text-left bg-[#F0F3FF4D]">
          <tr className="text-[#1F2937] text-[12px] font-bold h-16">
            <th className="p-4">REPORT NAME</th>
            <th>GENERATED BY</th>
            <th>DEPARTMENT</th>
            <th>DATE</th>
            <th>STATUS</th>
            <th>ACTIONS</th>
          </tr>
        </thead>

        <tbody>
          {currentData.map((report, index) => (
            <tr key={index} className="h-25 text-[#001C3B]">
              <td className="p-4 font-bold text-[14px] ">{report.name}</td>
              <td className=" text-[14px] font-normal">{report.user}</td>
              <td className="text-[14px] font-normal">{report.department}</td>
              <td className="text-[#4A4455] text-[14px] font-normal">
                {report.date}
              </td>

              <td>
                <span
                  className={` rounded-xl font-bold   text-xs ${
                    report.status === "Ready"
                      ? "bg-[#F0FDFA] text-[#0F766E] px-[1.5px] py-2.5"
                      : " text-[#D97706] flex items-center "
                  }`}
                >
                  {report.status === "Processing" && <GoDotFill />}
                  {report.status}
                </span>
              </td>

              <td>
                {report.status === "Ready" ? (
                  <button className="text-[#0029F5] font-bold text-[14px] flex items-center gap-2">
                    <AiOutlineDownload color="#0029F5" /> Download
                  </button>
                ) : (
                  <span className="text-[#4A445566] font-bold text-[14px]  flex items-center gap-2">
                    {" "}
                    <AiOutlineDownload /> Download
                  </span>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Pagination */}
      <div className="flex justify-between items-center p-4 font-medium text-xs text-[#4A4455]">
        <p>
          Showing {currentData.length} of {filtered.length} reports
        </p>

        <div className="flex gap-5 text-[#001C3B] text-[20px]">
          <button
            onClick={() => setCurrentPage((p) => Math.max(p - 1, 1))}
            className="cursor-pointer"
          >
            &lt;
          </button>
          <button
            onClick={() => setCurrentPage((p) => Math.min(p + 1, totalPages))}
            className="cursor-pointer"
          >
            &gt;
          </button>
        </div>
      </div>
    </div>
  );
};

export default ReportsTable;
